update=18.08.2015 00:19:39
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=../Kicad_Lib;../Kicad_Lib/borniers
[eeschema/libraries]
LibName1=StepperController-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=microcontrollers
LibName11=microchip
LibName12=texas
LibName13=interface
LibName14=display
LibName15=siliconi
LibName16=opto
LibName17=atmel
LibName18=contrib
LibName19=C:/KiCad/share/library/brooktre
LibName20=C:/KiCad/share/library/dc-dc
LibName21=C:/KiCad/share/library/elec-unifil
LibName22=C:/KiCad/share/library/ftdi
LibName23=C:/KiCad/share/library/graphic
LibName24=C:/KiCad/share/library/logo
LibName25=C:/KiCad/share/library/relays
LibName26=w_connectors
LibName27=w_device
LibName28=w_microcontrollers
LibName29=w_opto
LibName30=w_relay
LibName31=w_transistor
LibName32=borniers/borniers
LibName33=D:/Eigene Dateien/Dokumente/Projekte/KiCad/tmc2660
LibName34=clock_oscillator_x014s/xo-14s
LibName35=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName36=C:/Program Files/KiCad/share/kicad/library/74xx
LibName37=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName38=C:/Program Files/KiCad/share/kicad/library/actel
LibName39=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName40=C:/Program Files/KiCad/share/kicad/library/Altera
LibName41=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName42=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName43=C:/Program Files/KiCad/share/kicad/library/atmel
LibName44=C:/Program Files/KiCad/share/kicad/library/audio
LibName45=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName46=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName47=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName48=C:/Program Files/KiCad/share/kicad/library/conn
LibName49=C:/Program Files/KiCad/share/kicad/library/contrib
LibName50=C:/Program Files/KiCad/share/kicad/library/cypress
LibName51=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName52=C:/Program Files/KiCad/share/kicad/library/device
LibName53=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName54=C:/Program Files/KiCad/share/kicad/library/diode
LibName55=C:/Program Files/KiCad/share/kicad/library/display
LibName56=C:/Program Files/KiCad/share/kicad/library/dsp
LibName57=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName58=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName59=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName60=C:/Program Files/KiCad/share/kicad/library/gennum
LibName61=C:/Program Files/KiCad/share/kicad/library/graphic
LibName62=C:/Program Files/KiCad/share/kicad/library/hc11
LibName63=C:/Program Files/KiCad/share/kicad/library/intel
LibName64=C:/Program Files/KiCad/share/kicad/library/interface
LibName65=C:/Program Files/KiCad/share/kicad/library/ir
LibName66=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName67=C:/Program Files/KiCad/share/kicad/library/linear
LibName68=C:/Program Files/KiCad/share/kicad/library/logo
LibName69=C:/Program Files/KiCad/share/kicad/library/maxim
LibName70=C:/Program Files/KiCad/share/kicad/library/memory
LibName71=C:/Program Files/KiCad/share/kicad/library/microchip
LibName72=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName73=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName74=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName75=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName76=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName77=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName78=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName79=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName80=C:/Program Files/KiCad/share/kicad/library/motorola
LibName81=C:/Program Files/KiCad/share/kicad/library/msp430
LibName82=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName83=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName84=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName85=C:/Program Files/KiCad/share/kicad/library/opto
LibName86=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName87=C:/Program Files/KiCad/share/kicad/library/philips
LibName88=C:/Program Files/KiCad/share/kicad/library/power
LibName89=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName90=C:/Program Files/KiCad/share/kicad/library/powerint
LibName91=C:/Program Files/KiCad/share/kicad/library/pspice
LibName92=C:/Program Files/KiCad/share/kicad/library/references
LibName93=C:/Program Files/KiCad/share/kicad/library/regul
LibName94=C:/Program Files/KiCad/share/kicad/library/relays
LibName95=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName96=C:/Program Files/KiCad/share/kicad/library/sensors
LibName97=C:/Program Files/KiCad/share/kicad/library/silabs
LibName98=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName99=C:/Program Files/KiCad/share/kicad/library/stm8
LibName100=C:/Program Files/KiCad/share/kicad/library/stm32
LibName101=C:/Program Files/KiCad/share/kicad/library/supertex
LibName102=C:/Program Files/KiCad/share/kicad/library/switches
LibName103=C:/Program Files/KiCad/share/kicad/library/texas
LibName104=C:/Program Files/KiCad/share/kicad/library/transf
LibName105=C:/Program Files/KiCad/share/kicad/library/transistors
LibName106=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName107=C:/Program Files/KiCad/share/kicad/library/valves
LibName108=C:/Program Files/KiCad/share/kicad/library/video
LibName109=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName110=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName111=C:/Program Files/KiCad/share/kicad/library/Zilog
