update=04.03.2016 00:19:01
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=../../../KiCad/Kicad_Lib;../../../KiCad/Kicad_Lib/borniers;../../../KiCad/Kicad_Lib/clock_oscillator_x014s;../../../KiCad/Kicad_Lib/converted
[eeschema/libraries]
LibName1=StepperController-rescue
LibName2=C:/KiCad/share/library/brooktre
LibName3=C:/KiCad/share/library/dc-dc
LibName4=C:/KiCad/share/library/elec-unifil
LibName5=C:/KiCad/share/library/ftdi
LibName6=C:/KiCad/share/library/graphic
LibName7=C:/KiCad/share/library/logo
LibName8=C:/KiCad/share/library/relays
LibName9=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName10=C:/Program Files/KiCad/share/kicad/library/74xx
LibName11=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName12=C:/Program Files/KiCad/share/kicad/library/actel
LibName13=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName14=C:/Program Files/KiCad/share/kicad/library/Altera
LibName15=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName16=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName17=C:/Program Files/KiCad/share/kicad/library/atmel
LibName18=C:/Program Files/KiCad/share/kicad/library/audio
LibName19=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName20=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName21=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName22=C:/Program Files/KiCad/share/kicad/library/conn
LibName23=C:/Program Files/KiCad/share/kicad/library/contrib
LibName24=C:/Program Files/KiCad/share/kicad/library/cypress
LibName25=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName26=C:/Program Files/KiCad/share/kicad/library/device
LibName27=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName28=C:/Program Files/KiCad/share/kicad/library/diode
LibName29=C:/Program Files/KiCad/share/kicad/library/display
LibName30=C:/Program Files/KiCad/share/kicad/library/dsp
LibName31=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName32=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName33=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName34=C:/Program Files/KiCad/share/kicad/library/gennum
LibName35=C:/Program Files/KiCad/share/kicad/library/graphic
LibName36=C:/Program Files/KiCad/share/kicad/library/hc11
LibName37=C:/Program Files/KiCad/share/kicad/library/intel
LibName38=C:/Program Files/KiCad/share/kicad/library/interface
LibName39=C:/Program Files/KiCad/share/kicad/library/ir
LibName40=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName41=C:/Program Files/KiCad/share/kicad/library/linear
LibName42=C:/Program Files/KiCad/share/kicad/library/logo
LibName43=C:/Program Files/KiCad/share/kicad/library/maxim
LibName44=C:/Program Files/KiCad/share/kicad/library/memory
LibName45=C:/Program Files/KiCad/share/kicad/library/microchip
LibName46=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName47=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName48=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName49=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName51=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName52=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName53=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName54=C:/Program Files/KiCad/share/kicad/library/motorola
LibName55=C:/Program Files/KiCad/share/kicad/library/msp430
LibName56=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName57=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName58=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName59=C:/Program Files/KiCad/share/kicad/library/opto
LibName60=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName61=C:/Program Files/KiCad/share/kicad/library/philips
LibName62=C:/Program Files/KiCad/share/kicad/library/power
LibName63=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName64=C:/Program Files/KiCad/share/kicad/library/powerint
LibName65=C:/Program Files/KiCad/share/kicad/library/pspice
LibName66=C:/Program Files/KiCad/share/kicad/library/references
LibName67=C:/Program Files/KiCad/share/kicad/library/regul
LibName68=C:/Program Files/KiCad/share/kicad/library/relays
LibName69=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName70=C:/Program Files/KiCad/share/kicad/library/sensors
LibName71=C:/Program Files/KiCad/share/kicad/library/silabs
LibName72=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName73=C:/Program Files/KiCad/share/kicad/library/stm8
LibName74=C:/Program Files/KiCad/share/kicad/library/stm32
LibName75=C:/Program Files/KiCad/share/kicad/library/supertex
LibName76=C:/Program Files/KiCad/share/kicad/library/switches
LibName77=C:/Program Files/KiCad/share/kicad/library/texas
LibName78=C:/Program Files/KiCad/share/kicad/library/transf
LibName79=C:/Program Files/KiCad/share/kicad/library/transistors
LibName80=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName81=C:/Program Files/KiCad/share/kicad/library/valves
LibName82=C:/Program Files/KiCad/share/kicad/library/video
LibName83=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName84=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName85=C:/Program Files/KiCad/share/kicad/library/Zilog
[general]
version=1
